--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-06-06 12:19:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 17832)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17838)
-- Name: klient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.klient (
    id integer NOT NULL,
    imie character varying(150) NOT NULL,
    nazwisko character varying(150) NOT NULL,
    telefon character varying(20)
);


ALTER TABLE public.klient OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 17837)
-- Name: klient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.klient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.klient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17843)
-- Name: model_kod; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.model_kod (
    kod_modelu character varying(100) NOT NULL,
    marka character varying(100) NOT NULL,
    pelna_nazwa character varying(200) NOT NULL
);


ALTER TABLE public.model_kod OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17849)
-- Name: wpis_serwisowy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wpis_serwisowy (
    id integer NOT NULL,
    klient_id integer NOT NULL,
    kod_modelu character varying(100) NOT NULL,
    imei character varying(50),
    opis text,
    cena_wstepna numeric,
    cena_koncowa numeric
);


ALTER TABLE public.wpis_serwisowy OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17848)
-- Name: wpis_serwisowy_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wpis_serwisowy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wpis_serwisowy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4865 (class 0 OID 17832)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250606095356_InitDb	9.0.5
20250606101524_simpleSeed	9.0.5
\.


--
-- TOC entry 4867 (class 0 OID 17838)
-- Dependencies: 219
-- Data for Name: klient; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.klient (id, imie, nazwisko, telefon) FROM stdin;
1	Adrian	Kowalczyk	123123123
2	Kondrat	Kwaśniak	415617154
3	Karol	Marek	918472948
\.


--
-- TOC entry 4868 (class 0 OID 17843)
-- Dependencies: 220
-- Data for Name: model_kod; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.model_kod (kod_modelu, marka, pelna_nazwa) FROM stdin;
MI12PRO	Xiaomi	Xiaomi 12 Pro
PIXEL7P	Google	Google Pixel 7 Pro
REDMIN10	Xiaomi	Redmi Note 10
SM-A525F	Samsung	Samsung Galaxy A52
\.


--
-- TOC entry 4870 (class 0 OID 17849)
-- Dependencies: 222
-- Data for Name: wpis_serwisowy; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wpis_serwisowy (id, klient_id, kod_modelu, imei, opis, cena_wstepna, cena_koncowa) FROM stdin;
1	1	PIXEL7P	123456789012345	Telefon się nie włącza, możliwe zalanie cieczą.	50.0	\N
2	1	MI12PRO	123456789012345	Rozbity ekran	550.0	600.0
3	2	REDMIN10	123461719012345	Telefon się nie włącza, oraz nie reaguje na podpięcie do ładowarki.	35.0	\N
\.


--
-- TOC entry 4876 (class 0 OID 0)
-- Dependencies: 218
-- Name: klient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.klient_id_seq', 4, false);


--
-- TOC entry 4877 (class 0 OID 0)
-- Dependencies: 221
-- Name: wpis_serwisowy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wpis_serwisowy_id_seq', 4, false);


--
-- TOC entry 4709 (class 2606 OID 17836)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4711 (class 2606 OID 17842)
-- Name: klient PK_klient; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.klient
    ADD CONSTRAINT "PK_klient" PRIMARY KEY (id);


--
-- TOC entry 4713 (class 2606 OID 17847)
-- Name: model_kod PK_model_kod; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_kod
    ADD CONSTRAINT "PK_model_kod" PRIMARY KEY (kod_modelu);


--
-- TOC entry 4717 (class 2606 OID 17855)
-- Name: wpis_serwisowy PK_wpis_serwisowy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wpis_serwisowy
    ADD CONSTRAINT "PK_wpis_serwisowy" PRIMARY KEY (id);


--
-- TOC entry 4714 (class 1259 OID 17866)
-- Name: IX_wpis_serwisowy_klient_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_wpis_serwisowy_klient_id" ON public.wpis_serwisowy USING btree (klient_id);


--
-- TOC entry 4715 (class 1259 OID 17867)
-- Name: IX_wpis_serwisowy_kod_modelu; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_wpis_serwisowy_kod_modelu" ON public.wpis_serwisowy USING btree (kod_modelu);


--
-- TOC entry 4718 (class 2606 OID 17856)
-- Name: wpis_serwisowy FK_wpis_serwisowy_klient_klient_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wpis_serwisowy
    ADD CONSTRAINT "FK_wpis_serwisowy_klient_klient_id" FOREIGN KEY (klient_id) REFERENCES public.klient(id) ON DELETE CASCADE;


--
-- TOC entry 4719 (class 2606 OID 17861)
-- Name: wpis_serwisowy FK_wpis_serwisowy_model_kod_kod_modelu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wpis_serwisowy
    ADD CONSTRAINT "FK_wpis_serwisowy_model_kod_kod_modelu" FOREIGN KEY (kod_modelu) REFERENCES public.model_kod(kod_modelu) ON DELETE CASCADE;


-- Completed on 2025-06-06 12:19:37

--
-- PostgreSQL database dump complete
--

