CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE klient (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    imie character varying(150) NOT NULL,
    nazwisko character varying(150) NOT NULL,
    telefon character varying(20),
    CONSTRAINT "PK_klient" PRIMARY KEY (id)
);

CREATE TABLE model_kod (
    kod_modelu character varying(100) NOT NULL,
    marka character varying(100) NOT NULL,
    pelna_nazwa character varying(200) NOT NULL,
    CONSTRAINT "PK_model_kod" PRIMARY KEY (kod_modelu)
);

CREATE TABLE wpis_serwisowy (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    klient_id integer NOT NULL,
    kod_modelu character varying(100) NOT NULL,
    imei character varying(50),
    opis text,
    cena_wstepna numeric,
    cena_koncowa numeric,
    CONSTRAINT "PK_wpis_serwisowy" PRIMARY KEY (id),
    CONSTRAINT "FK_wpis_serwisowy_klient_klient_id" FOREIGN KEY (klient_id) REFERENCES klient (id) ON DELETE CASCADE,
    CONSTRAINT "FK_wpis_serwisowy_model_kod_kod_modelu" FOREIGN KEY (kod_modelu) REFERENCES model_kod (kod_modelu) ON DELETE CASCADE
);

CREATE INDEX "IX_wpis_serwisowy_klient_id" ON wpis_serwisowy (klient_id);

CREATE INDEX "IX_wpis_serwisowy_kod_modelu" ON wpis_serwisowy (kod_modelu);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250606095356_InitDb', '9.0.5');

INSERT INTO klient (id, imie, nazwisko, telefon)
VALUES (1, 'Adrian', 'Kowalczyk', '123123123');
INSERT INTO klient (id, imie, nazwisko, telefon)
VALUES (2, 'Kondrat', 'Kwaśniak', '415617154');
INSERT INTO klient (id, imie, nazwisko, telefon)
VALUES (3, 'Karol', 'Marek', '918472948');

INSERT INTO model_kod (kod_modelu, marka, pelna_nazwa)
VALUES ('MI12PRO', 'Xiaomi', 'Xiaomi 12 Pro');
INSERT INTO model_kod (kod_modelu, marka, pelna_nazwa)
VALUES ('PIXEL7P', 'Google', 'Google Pixel 7 Pro');
INSERT INTO model_kod (kod_modelu, marka, pelna_nazwa)
VALUES ('REDMIN10', 'Xiaomi', 'Redmi Note 10');
INSERT INTO model_kod (kod_modelu, marka, pelna_nazwa)
VALUES ('SM-A525F', 'Samsung', 'Samsung Galaxy A52');

INSERT INTO wpis_serwisowy (id, cena_koncowa, cena_wstepna, imei, klient_id, kod_modelu, opis)
VALUES (1, NULL, 50.0, '123456789012345', 1, 'PIXEL7P', 'Telefon się nie włącza, możliwe zalanie cieczą.');
INSERT INTO wpis_serwisowy (id, cena_koncowa, cena_wstepna, imei, klient_id, kod_modelu, opis)
VALUES (2, 600.0, 550.0, '123456789012345', 1, 'MI12PRO', 'Rozbity ekran');
INSERT INTO wpis_serwisowy (id, cena_koncowa, cena_wstepna, imei, klient_id, kod_modelu, opis)
VALUES (3, NULL, 35.0, '123461719012345', 2, 'REDMIN10', 'Telefon się nie włącza, oraz nie reaguje na podpięcie do ładowarki.');

SELECT setval(
    pg_get_serial_sequence('klient', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM klient) + 1,
        nextval(pg_get_serial_sequence('klient', 'id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('wpis_serwisowy', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM wpis_serwisowy) + 1,
        nextval(pg_get_serial_sequence('wpis_serwisowy', 'id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250606101524_simpleSeed', '9.0.5');

COMMIT;

